INSERT INTO USER_ (USER_ID, USER_NAME, USER_PHONE)  
VALUES ('000001', 'Vlad', '80000000');

INSERT INTO USER_ (USER_ID, USER_NAME, USER_PHONE)  
VALUES ('000002', 'Vlud', '70000000');

INSERT INTO USER_ (USER_ID, USER_NAME, USER_PHONE)  
VALUES ('000003', 'Vlid', '60000000');

INSERT INTO CONTENT ("CONTENT_ID", "CONTENT")  
VALUES ('1', 'odjndfivdfnk');

INSERT INTO CONTENT ("CONTENT_ID", "CONTENT")  
VALUES ('2', 'bsdfbvdfbfgnfgh');

INSERT INTO CONTENT ("CONTENT_ID", "CONTENT")  
VALUES ('3', 'dfsvdfvfvfb');

INSERT INTO MESSENGERS ("MESENGER_ID", "MESSENGER_NAME")  
VALUES ('1', 'Telegram');

INSERT INTO MESSENGERS ("MESENGER_ID", "MESSENGER_NAME")  
VALUES ('2', 'VK');

INSERT INTO MESSENGERS ("MESENGER_ID", "MESSENGER_NAME")  
VALUES ('3', 'Viber') ;

INSERT INTO MESSAGE (TO_USER, ID_MESSANGER, FROM_USER, "MESSAGE_ID", ID_CONTENT, MASSAGE_TIME)  
VALUES ('1', '1', '2', '1','1', DATE '1980-12-17');

INSERT INTO MESSAGE (TO_USER, ID_MESSANGER, FROM_USER, "MESSAGE_ID", ID_CONTENT, MASSAGE_TIME)  
VALUES ('2', '1', '1', '2','1', DATE '2007-11-10');

INSERT INTO MESSAGE (TO_USER, ID_MESSANGER, FROM_USER, "MESSAGE_ID", ID_CONTENT, MASSAGE_TIME)  
VALUES ('3', '1', '1', '3','1', DATE '2018-11-10');
